# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        /:title/


# Setup
title:            JRP001
tagline:          'Engenharia de Software'
description:      'João Perin<br>Blog para troca de experiências em Desenvolvimento de Sistemas por um Engenheiro Nômade.'
url:              https://blog.jrperin.com
baseurl:          '/'

author:
  name:           'João Roberto Perin'
  url:            https://www.linkedin.com/in/jrperin/

paginate:         10

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/jrperin


# Gems
gems: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap

plugins: 
  - jekyll-paginate
  - jekyll-gist
  - jekyll-sitemap 