# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty


# Setup
title:            JRPerin
tagline:          'Engenharia de Software'
description:      'Troca de experiências em Engenharia de Software por um Engenheiro Nômade.'
url:              http://jrperin.com
baseurl:          ''

author:
  name:           'João Roberto Perin'
  url:            https://github/jrperin

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/jrperin
